"""
Catalogue des maladies — PlantVillage (38 classes reconnues par le CNN Keras).
Chaque entrée est indexée par le codeLabel produit par le modèle (ia/model.py,
class_names.json) et sert à peupler la collection MongoDB "recommandations"
(voir seed_recommandations.py) et à enrichir la réponse de /api/predict.
"""

CLASS_INFO = {
    "Apple___Apple_scab": {
        "plante": "Pomme 🍎",
        "maladie": "Tavelure",
        "niveau": "sick",
        "description": "Champignon Venturia inaequalis. Taches olivâtres puis brun-noir sur feuilles et fruits.",
        "traitement": "Fongicide cuivre ou captane dès le débourrement. Répéter après chaque pluie.",
        "conseil": "Ramasser et brûler les feuilles tombées. Tailler pour aérer la frondaison.",
    },
    "Apple___Black_rot": {
        "plante": "Pomme 🍎",
        "maladie": "Pourriture noire",
        "niveau": "critical",
        "description": "Champignon Botryosphaeria obtusa. Anneaux concentriques brun-noirs sur fruits, chancres sur rameaux.",
        "traitement": "Excision chirurgicale des parties atteintes. Fongicide systémique (thiophanate-méthyl).",
        "conseil": "Désinfection des outils de taille. Destruction des momies de fruits. Taille hivernale stricte.",
    },
    "Apple___Cedar_apple_rust": {
        "plante": "Pomme 🍎",
        "maladie": "Rouille cédrière",
        "niveau": "sick",
        "description": "Champignon Gymnosporangium juniperi-virginianae. Taches orange vif sur la face supérieure des feuilles.",
        "traitement": "Myclobutanil ou trifloxystrobine au stade bouton rose. 2-3 traitements espacés de 10 jours.",
        "conseil": "Supprimer les genévriers/cèdres à moins de 300 m. Variétés résistantes recommandées.",
    },
    "Apple___healthy": {
        "plante": "Pomme 🍎", "maladie": None, "niveau": "healthy",
        "description": "Feuille de pommier en parfaite santé, sans aucun signe de pathologie.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Maintenir l'irrigation régulière et la fertilisation équilibrée NPK.",
    },
    "Blueberry___healthy": {
        "plante": "Myrtille 🫐", "maladie": None, "niveau": "healthy",
        "description": "Plant de myrtillier en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Maintenir un pH acide (4.5–5.5). Paillis de copeaux de bois conseillé.",
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "plante": "Cerise 🍒", "maladie": "Oïdium", "niveau": "sick",
        "description": "Podosphaera clandestina. Feutrage blanc poudreux sur jeunes feuilles et pousses.",
        "traitement": "Soufre mouillable ou bicarbonate de sodium. Fongicide systémique si sévère.",
        "conseil": "Taille sévère pour aérer. Éviter l'excès d'azote. Arroser à la base.",
    },
    "Cherry_(including_sour)___healthy": {
        "plante": "Cerise 🍒", "maladie": None, "niveau": "healthy",
        "description": "Cerisier en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Taille après récolte. Protection filet contre les oiseaux.",
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "plante": "Maïs 🌽", "maladie": "Cercosporiose", "niveau": "sick",
        "description": "Cercospora zeae-maydis. Lésions rectangulaires gris-brun entre nervures, limitées par elles.",
        "traitement": "Triazole + strobilurine à partir de la feuille ligule (stade 9-11 feuilles).",
        "conseil": "Rotation maïs/soja. Hybrides résistants. Enfouissement des résidus.",
    },
    "Corn_(maize)___Common_rust_": {
        "plante": "Maïs 🌽", "maladie": "Rouille commune", "niveau": "sick",
        "description": "Puccinia sorghi. Pustules brun-rouille ovales sur les deux faces foliaires.",
        "traitement": "Fongicide triazole si pression forte avant floraison. Hybrides résistants préférables.",
        "conseil": "Infections tardives généralement sans impact économique. Surveiller dès début saison.",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "plante": "Maïs 🌽", "maladie": "Helminthosporiose", "niveau": "sick",
        "description": "Exserohilum turcicum. Grandes taches en forme de cigare, gris-vert puis brun-tan.",
        "traitement": "Propiconazole ou azoxystrobine + propiconazole au stade panicule.",
        "conseil": "Rotation obligatoire. Enfouissement profond des résidus.",
    },
    "Corn_(maize)___healthy": {
        "plante": "Maïs 🌽", "maladie": None, "niveau": "healthy",
        "description": "Plant de maïs en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Fertilisation azotée fractionnée. Irrigation en période de floraison.",
    },
    "Grape___Black_rot": {
        "plante": "Raisin 🍇", "maladie": "Pourriture noire", "niveau": "critical",
        "description": "Guignardia bidwellii. Taches circulaires brun-rouge avec pycnides noires, baies momifiées.",
        "traitement": "Mancozèbe ou cuivre en préventif. Traitement obligatoire avant floraison.",
        "conseil": "Éliminer les grappes momifiées. Palissage pour aérer. Taille courte.",
    },
    "Grape___Esca_(Black_Measles)": {
        "plante": "Raisin 🍇", "maladie": "Esca", "niveau": "critical",
        "description": "Complexe fongique du bois (Phaeomoniella, Phaeoacremonium). Tigré foliaire, apoplexie foudroyante.",
        "traitement": "Aucun traitement curatif. Protection des plaies de taille avec mastic fongicide.",
        "conseil": "Tailler par temps sec. Désinfecter outils (éthanol). Arracher plants très atteints.",
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "plante": "Raisin 🍇", "maladie": "Brûlure foliaire", "niveau": "sick",
        "description": "Pseudocercospora vitis. Taches angulaires brun-rougeâtre, jaunissement puis chute foliaire.",
        "traitement": "Cuivre + fongicide de contact. Éviter l'humidité stagnante.",
        "conseil": "Ramasser les feuilles tombées. Palissage soigné. Bonne gestion eau.",
    },
    "Grape___healthy": {
        "plante": "Raisin 🍇", "maladie": None, "niveau": "healthy",
        "description": "Feuille de vigne en parfaite santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Surveillance mildiou/oïdium. Taille hivernale rigoureuse.",
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "plante": "Orange 🍊", "maladie": "Verdissement des agrumes (HLB)", "niveau": "critical",
        "description": "Bactérie Candidatus Liberibacter asiaticus. Mosaïque asymétrique jaune-vert, fruits difformes et amers. INCURABLE.",
        "traitement": "Aucun traitement curatif. Arrachage et destruction immédiate des plants infectés.",
        "conseil": "QUARANTAINE STRICTE. Contrôle du psylle asiatique (vecteur). Plants certifiés indemnes obligatoires.",
    },
    "Peach___Bacterial_spot": {
        "plante": "Pêche 🍑", "maladie": "Tache bactérienne", "niveau": "sick",
        "description": "Xanthomonas arboricola pv. pruni. Petites taches aqueuses angulaires sur feuilles et fruits.",
        "traitement": "Oxychlorure de cuivre en préventif. Éviter aspersion sur feuillage.",
        "conseil": "Variétés résistantes disponibles. Éviter les blessures lors des travaux.",
    },
    "Peach___healthy": {
        "plante": "Pêche 🍑", "maladie": None, "niveau": "healthy",
        "description": "Pêcher en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Éclaircissage des fruits. Protection contre la cloque du pêcher au débourrement.",
    },
    "Pepper,_bell___Bacterial_spot": {
        "plante": "Poivron 🫑", "maladie": "Tache bactérienne", "niveau": "sick",
        "description": "Xanthomonas campestris pv. vesicatoria. Lésions aqueuses cernées de halo jaune, puis nécrotiques.",
        "traitement": "Cuivre + mancozèbe en préventif. Bactéricide (kasugamycine) si sévère.",
        "conseil": "Rotation 3 ans. Semences certifiées. Arrosage au sol uniquement.",
    },
    "Pepper,_bell___healthy": {
        "plante": "Poivron 🫑", "maladie": None, "niveau": "healthy",
        "description": "Plant de poivron en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Tuteurage recommandé. Température optimale 18–30°C.",
    },
    "Potato___Early_blight": {
        "plante": "Pomme de terre 🥔", "maladie": "Alternariose (mildiou précoce)", "niveau": "sick",
        "description": "Alternaria solani. Taches brunes concentriques en cible, sur feuilles les plus âgées d'abord.",
        "traitement": "Chlorothalonil ou mancozèbe préventif dès fermeture du couvert végétal.",
        "conseil": "Rotation 3 ans. Plants certifiés. Binage pour aération.",
    },
    "Potato___Late_blight": {
        "plante": "Pomme de terre 🥔", "maladie": "Mildiou (Phytophthora infestans)", "niveau": "critical",
        "description": "Phytophthora infestans. Taches huileuses brun-violet, duvet blanc en face inférieure. Progression fulgurante.",
        "traitement": "TRAITEMENT D'URGENCE : métalaxyl + mancozèbe. Détruire les fanes. Récolte rapide.",
        "conseil": "Surveiller les alertes mildiou (températures 15-20°C + humidité). Rotation obligatoire 4 ans.",
    },
    "Potato___healthy": {
        "plante": "Pomme de terre 🥔", "maladie": None, "niveau": "healthy",
        "description": "Plant de pomme de terre en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Buttage régulier. Irrigation goutte-à-goutte recommandée.",
    },
    "Raspberry___healthy": {
        "plante": "Framboise 🫐", "maladie": None, "niveau": "healthy",
        "description": "Framboisier en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Tailler les cannes fruitées après récolte. Paillage du sol recommandé.",
    },
    "Soybean___healthy": {
        "plante": "Soja 🌱", "maladie": None, "niveau": "healthy",
        "description": "Plant de soja en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Inoculation rhizobium recommandée. Rotation maïs-soja classique.",
    },
    "Squash___Powdery_mildew": {
        "plante": "Courge 🎃", "maladie": "Oïdium", "niveau": "sick",
        "description": "Podosphaera xanthii. Poudre blanche farineuse sur la face supérieure des feuilles.",
        "traitement": "Soufre mouillable ou bicarbonate dilué. Fongicide systémique si généralisé.",
        "conseil": "Aération. Éviter excès d'azote. Variétés tolérantes disponibles.",
    },
    "Strawberry___Leaf_scorch": {
        "plante": "Fraise 🍓", "maladie": "Brûlure des feuilles", "niveau": "sick",
        "description": "Diplocarpon earlianum. Petites taches pourpres à brun sur feuilles, sans tache centrale pâle.",
        "traitement": "Captane ou myclobutanil. Éliminer les feuilles infectées.",
        "conseil": "Éviter humidité persistante. Renouveler les plants tous les 3–4 ans.",
    },
    "Strawberry___healthy": {
        "plante": "Fraise 🍓", "maladie": None, "niveau": "healthy",
        "description": "Fraisier en bonne santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Paillis pour garder l'humidité et éviter les éclaboussures de terre.",
    },
    "Tomato___Bacterial_spot": {
        "plante": "Tomate 🍅", "maladie": "Tache bactérienne", "niveau": "sick",
        "description": "Xanthomonas spp. Petites taches aqueuses, puis nécrotiques entourées d'un halo jaune.",
        "traitement": "Cuivre + mancozèbe dès les premiers symptômes. Retirer feuilles infectées.",
        "conseil": "Rotation 2–3 ans. Arrosage au sol uniquement. Désinfection des outils.",
    },
    "Tomato___Early_blight": {
        "plante": "Tomate 🍅", "maladie": "Alternariose", "niveau": "sick",
        "description": "Alternaria solani. Taches brunes concentriques en cible, anneau jaune autour.",
        "traitement": "Chlorothalonil ou azoxystrobine. Supprimer feuilles basses infectées.",
        "conseil": "Paillis pour éviter éclaboussures. Arrosage matinal.",
    },
    "Tomato___Late_blight": {
        "plante": "Tomate 🍅", "maladie": "Mildiou (Phytophthora infestans)", "niveau": "critical",
        "description": "Phytophthora infestans. Taches huileuses irrégulières, duvet blanc sous les feuilles. Extrêmement contagieux.",
        "traitement": "URGENCE : fongicide systémique (métalaxyl + cuivre). Arracher plants très atteints.",
        "conseil": "Abri en cas de pluie. Brûler les débris. Ne jamais composter. Rotation stricte.",
    },
    "Tomato___Leaf_Mold": {
        "plante": "Tomate 🍅", "maladie": "Moisissure des feuilles (Cladosporiose)", "niveau": "sick",
        "description": "Passalora fulva. Face supérieure jaune, face inférieure veloutée olive à brun.",
        "traitement": "Mancozèbe ou chlorothalonil. Améliorer drastiquement la ventilation.",
        "conseil": "Humidité relative < 85%. Espacer les plants. Serre bien ventilée.",
    },
    "Tomato___Septoria_leaf_spot": {
        "plante": "Tomate 🍅", "maladie": "Septoriose", "niveau": "sick",
        "description": "Septoria lycopersici. Petites taches circulaires blanches à centre gris, nombreux points noirs.",
        "traitement": "Cuivre ou chlorothalonil. Supprimer feuilles basses au moindre symptôme.",
        "conseil": "Éviter arrosage foliaire. Rotation des cultures. Tuteurage.",
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "plante": "Tomate 🍅", "maladie": "Infestation d'acariens (Tetranychus urticae)", "niveau": "sick",
        "description": "Acarien Tetranychus urticae. Décoloration en mosaïque bronze, toiles fines sous les feuilles.",
        "traitement": "Acaricide (abamectine). Savon insecticide bio. Prédateurs biologiques (Phytoseiulus).",
        "conseil": "Hygrométrie élevée défavorable. Surveiller régulièrement la face inférieure.",
    },
    "Tomato___Target_Spot": {
        "plante": "Tomate 🍅", "maladie": "Tache en cible (Corynespora)", "niveau": "sick",
        "description": "Corynespora cassiicola. Taches concentriques brun-tan sur feuilles et fruits.",
        "traitement": "Azoxystrobine ou difénoconazole.",
        "conseil": "Bonne ventilation. Éliminer débris végétaux. Rotation des cultures.",
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "plante": "Tomate 🍅", "maladie": "Virus TYLCV", "niveau": "critical",
        "description": "Geminiviridae transmis par Bemisia tabaci. Feuilles en cuillère, chlorose marginale. INCURABLE.",
        "traitement": "Aucun traitement curatif. Insecticide contre les aleurodes (vecteur). Filet insectproof.",
        "conseil": "Variétés résistantes TYLCV disponibles. Éliminer plants atteints sans tarder. Quarantaine.",
    },
    "Tomato___Tomato_mosaic_virus": {
        "plante": "Tomate 🍅", "maladie": "Virus mosaïque (ToMV)", "niveau": "critical",
        "description": "Tobamovirus. Mosaïque vert clair/foncé, déformation foliaire et des fruits. Très contagieux par contact.",
        "traitement": "Aucun traitement curatif. Arracher et brûler immédiatement les plants infectés.",
        "conseil": "Hygiène stricte : laver les mains, désinfecter outils. Plants certifiés indemnes.",
    },
    "Tomato___healthy": {
        "plante": "Tomate 🍅", "maladie": None, "niveau": "healthy",
        "description": "Plant de tomate en parfaite santé.",
        "traitement": "Aucun traitement requis.",
        "conseil": "Tuteurage et taille des gourmands. Fertilisation régulière calcium/magnésium.",
    },
}
